version: '3'

services:
  mongo:
    image: mongo:6.0.4
    container_name: mongo
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"